version: "3"
services:
  api:
    build: .
    volumes:
      - .:/go/src/github.com/droptheplot/flashcards
    networks:
      - default-network
    depends_on:
      - postgres
      - redis
    command: fresh
    ports:
      - "8080:8080"
    env_file:
      - .env
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default-network
    expose:
      - "5432"
    ports:
      - "5432:5432"
  redis:
    image: redis:3-alpine
    ports:
      - "6379:6379"
    networks:
      - default-network
  # prometheus:
    # image: prom/prometheus
    # expose:
      # - "9090"
    # ports:
      # - "9090:9090"
    # volumes:
      # - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # networks:
      # - default-network
  # grafana:
    # image: grafana/grafana:latest
    # ports:
      # - "3000:3000"
    # depends_on:
      # - prometheus
    # networks:
      # - default-network
    # volumes:
      # - ./grafana:/var/lib/grafana
networks:
  default-network:
