version: "3"
services:
  api:
    build: .
    volumes:
      - .:/go/src/github.com/droptheplot/flashcards
    networks:
      - default-network
    depends_on:
      - db
    command: fresh
    ports:
      - "8080:8080"
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default-network
    expose:
      - "5432"
    ports:
      - "5432:5432"
  redis:
    image: redis:3-alpine
    ports:
      - "6379:6379"
    networks:
      - default-network
networks:
  default-network:
