{
 "title": "Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "name",
   "targets": [
    {
     "expr": "go_info{job=\"api\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  }
 ]
}