CREATE TABLE cards_sources (
  id SERIAL PRIMARY KEY,
  card_id INTEGER REFERENCES cards(id) ON DELETE CASCADE ON UPDATE CASCADE,
  source_id INTEGER REFERENCES sources(id) ON DELETE CASCADE ON UPDATE CASCADE
);
